// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocswmezbdaomlkgnyxob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jc3dtZXpiZGFvbWxrZ255eG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzM3MjksImV4cCI6MjA2Njc0OTcyOX0.zzcIH0Q-WKvGQBWzacNrR72SCc560rq6h8Rxo_mAAu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);